src/Django/ground_truth_videography_project/ground_truth/urls.py
from django.urls import path

from . import views

app_name = 'ground_truth'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('collections/', views.collections, name='collections'),
    path('<slug:audio_slug>/', views.audio, name='audio'),
    path('<slug:audio_slug>/<slug:chunk_slug>/', views.chunk, name='chunk'),
    path('<slug:audio_slug>/video', views.video, name='video'),
    path('<slug:audio_slug>/ground-truth', views.ground_truth, name='ground-truth'),
]

src/Django/ground_truth_videography_project/ground_truth_videography_project/urls.py
from django.contrib import admin
from django.urls import include, path
from ground_truth import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('ground-truth/', include('ground_truth.urls')),
    path('admin/', admin.site.urls),
]

src/Django/ground_truth_videography_project/ground_truth/models.py
from django.db import models
from django.template.defaultfilters import slugify
import json

class Audio(models.Model):
    music = models.BooleanField(default=True)
    artist = models.CharField(max_length=50, null=True)
    title = models.CharField(max_length=50, null=True)
    filename = models.CharField(max_length=50)
    transcript = models.TextField(null=True)
    coverart_colour = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    _ground_truth = models.CharField(max_length=1000)

    @property
    def ground_truth(self):
        return self._ground_truth
    
    @ground_truth.setter
    def ground_truth(self, value):
        self._ground_truth = json.dumps(value, indent=4, ensure_ascii=False)
    
    def save(self, delete, *args, **kwargs):
        if self.music:
            self.slug = slugify(f"{self.artist}-{self.title}")
        else:
            self.slug = slugify(self.filename)
        
        # Delete any existing records of the same track.
        if delete:
            Audio.objects.filter(slug=self.slug).delete()
        
        super(Audio, self).save(*args, **kwargs)
    
    def __str__(self):
        return f"{self.artist} - {self.title}"
    
    class Meta:
        verbose_name_plural = 'Audio Sources'

class Chunk(models.Model):
    index = models.IntegerField(blank=True)
    text = models.CharField(max_length=200)
    audio = models.ForeignKey(Audio, on_delete=models.CASCADE, default=1)
    start_time = models.FloatField()
    end_time = models.FloatField()
    _image_ids = models.CharField(max_length=500)
    _selected_ids = models.CharField(max_length=500)
    slug = models.SlugField()

    @property
    def image_ids(self):
        return json.loads(self._image_ids)
    
    @image_ids.setter
    def image_ids(self, value):
        self._image_ids = json.dumps(value)

    @property
    def selected_ids(self):
        return json.loads(self._selected_ids)
    
    @selected_ids.setter
    def selected_ids(self, value):
        self._selected_ids = json.dumps(value)
    
    @property
    def duration(self):
        return self.end_time - self.start_time

    def save(self, *args, **kwargs):
        self.slug = f"chunk-{slugify(self.index)}"
        super(Chunk, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.audio} | Chunk {self.index}"
    
    class Meta: 
        verbose_name_plural = 'Chunks'

src/Django/ground_truth_videography_project/ground_truth/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

def validate_youtubeURL(url):
    if not url.startswith("https://www.youtube.com/watch?v="):
        raise ValidationError(_("%(url)s is not a valid YouTube URL"), params={"url": url},)

class LinkForm(forms.Form):
    youtube_url = forms.CharField(
        label='', 
        max_length=100, 
        widget=forms.TextInput(attrs={'rows': 1, 'class': 'form-control', 'id': 'inputURL'}),
        validators=[validate_youtubeURL]
    )

src/Django/ground_truth_videography_project/ground_truth/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.conf import settings

from .models import Audio, Chunk
from .forms import LinkForm

from utilities.audio_retriever import clear_directories, download_yt, save_file
from utilities.audio_recogniser import recognise_audio, get_coverart_colour
from utilities.synced_transcription_retriever import get_synced_lyrics, seconds_to_time, transcribe_audio
from utilities.image_retriever import CLIP, index_image_paths
from utilities.videography import build_video
from utilities.ground_truth_builder import build_ground_truth

import os
import pylrc
import numpy as np
import json


SRC_FOLDER = "utilities"
IMAGE_PATHS = np.delete(index_image_paths(os.path.relpath(settings.IMAGE_DATASET_DIR)), settings.EXCLUDE)
IMAGE_VECTOR_PATH = os.path.join(SRC_FOLDER, "image_vectors", "imagenet-1k-vecs-FILTERED.npy")

clip = CLIP(IMAGE_PATHS, IMAGE_VECTOR_PATH, multilingual=False)

def home(request):
    link_form = LinkForm()
    audio_path = None
    filename = None
    transcript = None
    music = True

    if request.method == "POST":
        clear_directories(["audio", "transcript"], SRC_FOLDER)

        if 'youtube_url' in request.POST:
            link_form = LinkForm(request.POST)

            if link_form.is_valid():
                yt, audio_path, transcript = download_yt(link_form.cleaned_data['youtube_url'], SRC_FOLDER) 
                filename = yt.video_id
        elif 'audio_file' in request.FILES:
            audio_file = request.FILES['audio_file']
            # Validate the file is of audio format
            if 'audio' in audio_file.content_type:
                audio_path = save_file(audio_file, os.path.join(SRC_FOLDER, 'audio'))
                filename = audio_file.name.rsplit('.', 1)[0]
        
        if audio_path:
            title, artist = recognise_audio(audio_path, filename)
            coverart_colour = f"rgba{get_coverart_colour(filename, SRC_FOLDER)}"

            if title and artist and not transcript:
                transcript = get_synced_lyrics(title, artist, SRC_FOLDER, filename)
            elif not title and not artist:
                title = yt.title
                artist = yt.author
                music = False
            
            if not transcript:
                print("Transcribing audio with Whisper...")
                transcript = transcribe_audio(artist, title, SRC_FOLDER, filename)
            
            audio = Audio(music=music, artist=artist, title=title, filename=filename, transcript=transcript, 
                coverart_colour=coverart_colour, _ground_truth="null")
            audio.save(True)
            return redirect(reverse('ground_truth:audio', kwargs={'audio_slug': audio.slug}))
        
    return render(request, 'ground_truth/home.html', {'link_form': link_form})


distinct_chunks = {}
def audio(request, audio_slug):
    audio = Audio.objects.get(slug=audio_slug)
    chunks = []

    instrumental = False

    if audio.transcript:
        instrumental = "♪ Instrumental ♪" in audio.transcript

        transcript = pylrc.parse(audio.transcript)
        id = 1

        for i in range(len(transcript) - 1):
            # Skip instrumental parts of the song
            if (transcript[i].text == "♪"):
                continue
            
            line = transcript[i]
            print(f"Chunk {id}: {line.text}")
            chunk = Chunk.objects.filter(index=id, audio__slug=audio.slug)

            if chunk.exists():
                print("Updating existing Chunk...")
                chunk.update(text=line.text, audio_id=audio.id, start_time=line.time, end_time=transcript[i+1].time, 
                    _image_ids=chunk[0]._image_ids, _selected_ids=chunk[0]._selected_ids)
                chunk = chunk[0]
            else:
                chunk = Chunk(index=id, text=line.text, audio_id=audio.id, start_time=line.time, 
                    end_time=transcript[i+1].time, _image_ids="[]", _selected_ids="[]")
                chunk.save()

            chunks.append(chunk)

            # Store chunks with the same text together.
            if chunk.text in distinct_chunks:
                distinct_chunks[chunk.text].add(chunk.id)
            else:
                distinct_chunks[chunk.text] = {chunk.id}
            
            id += 1
            
    context = {
        'audio': audio,
        'chunks': chunks,
        'instrumental': instrumental,
        'ground_truth_built': audio.ground_truth != "null",
    }
    return render(request, 'ground_truth/audio.html', context)


def chunk(request, audio_slug, chunk_slug):
    audio = Audio.objects.get(slug=audio_slug)
    chunk = Chunk.objects.get(slug=chunk_slug, audio__slug=audio_slug)

    print(chunk)

    if chunk.image_ids == []:
        print("Performing query...")
        chunk.image_ids = clip.query_prompt(chunk.text)
        chunk.save()

    if request.method == "POST":
        post = request.POST.dict()

        # Save selected image ids in all chunks with repeating text
        selected_ids = [int(k) for k in post.keys() if k.isdigit()]
        Chunk.objects.filter(id__in=distinct_chunks[chunk.text]).update(_selected_ids=json.dumps(selected_ids))

        redirect_chunk = chunk.slug
        if 'finish' in post:
            build_ground_truth(audio, Chunk.objects.filter(audio__slug=audio_slug).order_by("index"), IMAGE_PATHS, SRC_FOLDER)
            return redirect(reverse('ground_truth:ground-truth', kwargs={'audio_slug': audio.slug}))
        elif 'previous' in post:
            redirect_chunk = f"chunk-{chunk.index - 1}"
        elif 'next' in post:
            redirect_chunk = f"chunk-{chunk.index + 1}"
        
        return redirect(reverse('ground_truth:chunk', kwargs={'audio_slug': audio.slug, 'chunk_slug': redirect_chunk}))

    context = {
        'audio': audio,
        'chunk': chunk,
        'chunks': Chunk.objects.filter(audio__slug=audio_slug),
        'image_paths': clip.image_paths[chunk.image_ids],
        "start_time": seconds_to_time(chunk.start_time),
        "end_time": seconds_to_time(chunk.end_time)
    }
    return render(request, 'ground_truth/chunk.html', context)


def video(request, audio_slug):
    audio = Audio.objects.get(slug=audio_slug)
    
    video_path = os.path.join(SRC_FOLDER, "video", f"{audio.filename}.mp4")
    audio_path = os.path.join(SRC_FOLDER, "audio", f"{audio.filename}.mp3")

    if not os.path.exists(video_path) and os.path.exists(audio_path):
        print("Building Video...")
        build_video(Chunk.objects.filter(audio__slug=audio_slug).order_by("index"), clip, audio_path, video_path)

    context = {
        'audio': audio,
        'video_exists': os.path.exists(video_path),
    }
    return render(request, 'ground_truth/video.html', context)


def ground_truth(request, audio_slug):
    return render(request, 'ground_truth/ground_truth.html', {'audio': Audio.objects.get(slug=audio_slug)})


def about(request):
    return render(request, 'ground_truth/about.html')


def collections(request):
    return render(request, 'ground_truth/collections.html', {'audio_tracks': Audio.objects.all()})

src/Django/ground_truth_videography_project/templates/ground_truth/about.html
{% extends 'ground_truth/base.html' %}
{% load static %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/about.css' %}"/>
{% endblock %}

{% block title %}
    Videography - About
{% endblock %}

{% block body %}
    <div class="section-about">
        <h1 id="hdAbout">About</h1>

        <p class="paragraph-about">
            This tool is used to build ground truths for automatic videography systems for given audio sources. To try it yourself, navigate to the home page and input a YouTube URL of a video, or upload your own audio file. The system will attempt to recognise the title and artist if the source is found to be a music track and retrieve it's synced lyric transcript if available. If it is not a music track, the system will attempt to grab any available captions. If no captions exist, the system will attempt to manually transcribe the audio source.
            <br />
            Any previously processed audio sources can be found in the 'Collections' tab on the navigation bar.
        </p>

        <br />
        <h2 id="hdGroundTruth">Ground Truth Building</h2>
        <p class="paragraph-about">
            Once an audio source is processed and it's transcription is retrieved, you will be able to start building the ground truth by clicking on the 'Build Ground Truth' button. Alternatively, you can click into a particular audio chunk within the transcript. Each chunk will display ten images that are relevant to the text present in that audio chunk. To build the ground truth, for each chunk, select the images that you believe are the <b>most</b> relevant to the text. Once finished, the ground truth data that you have built will be available to download as a JSON file.
        </p>

        <br />
        <h2 id="hdVideography">Automatic Videography</h2>
        <p class="paragraph-about">
            This tool also provides the standard automatic videography tool itself. Once an audio source is processed, you can click on the 'Generate Video' button which will automatically generate a video with the audio source accompanied by relevant imagery based on the textual information present. The images will be chosen at random from the ranked ten for each audio chunk.
        </p>
    </div>
{% endblock %}

src/Django/ground_truth_videography_project/templates/ground_truth/audio.html
{% extends 'ground_truth/base.html' %}
{% load static %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base-extended.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/audio.css' %}"/>
{% endblock %}

{% block style %}
    <style>
        .link-lines:hover { background-color: {{ audio.coverart_colour }}; }
    </style>
{% endblock %}

{% block title %}
    {{ audio }}
{% endblock %}

{% block body %}
    <div class="section-audio" style="background-color: {{ audio.coverart_colour }}">
        <img src="{% static '/coverart/'|add:audio.filename|add:'.png' %}" id="imgCoverArt">
        <div class="section-audio_info">
            <h1 class="heading-audio" id="hdTitle">{{ audio.title }}</h1>
            <h2 class="heading-audio" id="hdArtist">{{ audio.artist }}</h2>

            <div class="section-start_button">
                {% if chunks|length %}
                    <a href="{% url 'ground_truth:video' audio.slug %}">
                        <button class="btn btn-primary button-start" id="btnGenerate">Generate Video</button>
                    </a>
                    {% if audio.ground_truth == "null" %}
                        <a href="{% url 'ground_truth:chunk' audio.slug chunks.0.slug %}">
                            <button class="btn btn-primary button-start" id="btnBuild">Build Ground Truth</button>
                        </a>
                    {% else %}
                        <a href="{% url 'ground_truth:ground-truth' audio.slug %}">
                            <button class="btn btn-primary button-start" id="btnBuild">Build Ground Truth</button>
                        </a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>

    <div class="section-transcript">
        {% if chunks|length %}
            {% for chunk in chunks %}
                <a href="{% url 'ground_truth:chunk' audio.slug chunk.slug %}" class="link-lines">{{ chunk.text }}</a><br />
            {% endfor %}
        {% elif instrumental %}
            <p id="parInstrumental" style="background-color: {{ audio.coverart_colour }}">♪ &nbsp&nbsp INSTRUMENTAL &nbsp&nbsp ♪</p>
        {% else %}
            <p id="parNoTranscript">No transcript found for this audio track</p>
        {% endif %}
    </div>
{% endblock %}

{% block scripts %}
    <script type="application/javascript" src="{% static 'js/audio.js' %}"></script>
{% endblock %}

src/Django/ground_truth_videography_project/templates/ground_truth/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Exo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
    {% block links %}
    {% endblock %}

    {% block style %}
    {% endblock %}

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"> </script>

    <title>
        {% block title %}
            Home
        {% endblock %}
    </title>
</head>

<body>
    <div class="section-title">
        <a href="{% url 'ground_truth:home' %}"><h1 class="heading-title">Automatic Videography Ground Truth Constructor</h1></a>
    </div>
    <div class="section-navbar">
        <a href="{% url 'ground_truth:about' %}">
            <button class="button-navbar">About</button>
        </a>
        <a href="{% url 'ground_truth:collections' %}">
            <button class="button-navbar">Collections</button>
        </a>
    </div>

    {% block body %}
    {% endblock %}

    <script type="application/javascript" src="{% static 'js/colourManipulator.js' %}"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>

src/Django/ground_truth_videography_project/templates/ground_truth/chunk.html
{% extends 'ground_truth/base.html' %}
{% load static %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base-extended.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/chunk.css' %}"/>
{% endblock %}

{% block style %}
    {% if chunk.index == 1 %}
        <style>
            #btnNext { margin-left: -80px; }
        </style>
    {% endif %}
{% endblock %}

{% block title %}
    {{ chunk }}
{% endblock %}

{% block body %}
    <div class="section-audio_subheading" style="background-color: {{ audio.coverart_colour }}">
        <a href="{% url 'ground_truth:audio' audio.slug %}"><h2 class="subheading-audio">{{ audio }}</h2></a>
    </div>

    <div class="section-chunk_info">
        <p id="parChunkNumber">Chunk {{ chunk.index }} of {{ chunks|length }}</p>
        <p id="parInstructions">Select the images that you perceive as being the most fitting to the text below:</p>
        <p id="parText" style="background-color: {{ audio.coverart_colour }}">{{ chunk.text }}</p>
    </div>

    <form method="POST">
        {% csrf_token %}
        <div class="section-chunk_nav">
            {% if chunk.index > 1 %}
                <input type="submit" name="previous" value="Previous" class="btn btn-primary button-nav" id="btnPrevious">
            {% endif %}
            
            <div class="section-images">
                {% for path in image_paths %}
                    <img src="{% static path %}" class="images-most_similar" name='{{ forloop.counter0 }}'>
                {% endfor %}
            </div>

            {% if chunk.index < chunks|length %}
                <input type="submit" name="next" value="Next" class="btn btn-primary button-nav" id="btnNext">
            {% else %}
                <input type="submit" name="finish" value="Finish" class="btn btn-primary button-nav" id="btnFinish">
            {% endif %}
        </div>
    </form>

    <div class="section-timestamp" style="background-color: {{ audio.coverart_colour }}">
        <p id="parTimestamp">Timestamp: {{ start_time }} - {{ end_time }}</p>
    </div>
{% endblock %}

{% block scripts %}
    <script type="application/javascript" src="{% static 'js/jquery.imgCheckBox.js' %}"></script>
    <script type="application/javascript" src="{% static 'js/chunk.js' %}"></script>
    <script>
        $(".images-most_similar").imgCheckbox({ 
            "graySelected": false, 
            "scaleSelected": false,
            "fadeCheckMark": true,
            "preselect": {{ chunk.selected_ids }},
            "styles": { 
                "span.imgCheckbox": {
                    "margin": "25px 25px 0px 25px",
                },

                "span.imgCheckbox.imgChked img": { 
                    "transform": "scale(1.12)",
                    "border": "5px solid #2dba52",
                }
            }
        });
    </script>
{% endblock %}

src/Django/ground_truth_videography_project/templates/ground_truth/collections.html
{% extends 'ground_truth/base.html' %}
{% load static %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/collections.css' %}"/>
{% endblock %}

{% block title %}
    Videography - Collections
{% endblock %}

{% block body %}
    <h1 id="hdCollections">Collections</h1>
    <div class="section-audio_links">
        {% for track in audio_tracks %}
            <a href="{% url 'ground_truth:audio' track.slug %}" class="link-tracks">
                <button class="button-tracks" style="background-color: {{ track.coverart_colour }}">{{ track }}</button>
            </a>
        {% endfor %}
    </div>
{% endblock %}

{% block scripts %}
    <script type="application/javascript" src="{% static 'js/collections.js' %}"></script>
{% endblock %}

src/Django/ground_truth_videography_project/templates/ground_truth/ground_truth.html
{% extends 'ground_truth/base.html' %}
{% load static %}

{% block links %}
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js?lang=js&amp;skin=sunburst"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/ground_truth.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/chunk.css' %}"/>
{% endblock %}

{% block title %}
    {{ audio }} | Ground Truth
{% endblock %}

{% block body %}
    <div class="section-audio_subheading" style="background-color: {{ audio.coverart_colour }}">
        <a href="{% url 'ground_truth:audio' audio.slug %}"><h2 class="subheading-audio">{{ audio }}</h2></a>
    </div>

    <div class="section-groundTruth">
    {% if audio.ground_truth != "null" %}
        <h1 id="hdGroundTruth">Ground Truth</h1>
        <pre id="preGroundTruth" class="prettyprint lang-scm">{{ audio.ground_truth }}</pre>

        <a href="{% static 'ground_truth/'|add:audio.filename|add:'.json' %}" download>
            <button class="btn btn-primary button-start" id="btnDownload">Download</button>
        </a>
    {% else %}
        <p id="parNoGroundTruth">No ground truth data has been built for <br /> <b>{{ audio }}</b></p>
        <a href="{% url 'ground_truth:chunk' audio.slug 'chunk-1' %}">
            <button class="btn btn-primary button-start" id="btnBuild">Build Ground Truth</button>
        </a>
    {% endif %}
    </div>
{% endblock %}


{% block scripts %}
    <script type="application/javascript" src="{% static 'js/chunk.js' %}"></script>
{% endblock %}

src/Django/ground_truth_videography_project/templates/ground_truth/home.html
{% extends 'ground_truth/base.html' %}
{% load static %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
{% endblock %}

{% block body %}
    <p id="parInfo">Enter a Youtube video URL below or, alternatively, upload your own audio file to start building a ground truth for your audio source.</p>

    <div class="section-url_input">
        <form method="POST">
            <label for="inputURL" class="form-label label-input" id="lblURL">Enter a YouTube video URL:</label>
            {% csrf_token %}
            {{ link_form.as_p }}
            <input type="submit" class="btn btn-primary button-submit">
        </form>
    </div>

    <p id="parOr">OR</p>

    <div class="section-file_input">
        <label for="inputFile" class="form-label label-input" id="lblFile">Upload an audio file:</label>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="audio_file" class="form-control" id="inputFile">
            <input type="submit" class="btn btn-primary button-submit">
        </form>
    </div>
{% endblock %}

src/Django/ground_truth_videography_project/templates/ground_truth/video.html
{% extends 'ground_truth/base.html' %}
{% load static %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base-extended.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/video.css' %}"/>
{% endblock %}

{% block title %}
    {{ audio }} | Video
{% endblock %}

{% block body %}
    <div class="section-audio_subheading" style="background-color: {{ audio.coverart_colour }}">
        <a href="{% url 'ground_truth:audio' audio.slug %}"><h2 class="subheading-audio">{{ audio }}</h2></a>
    </div>
    
    {% if video_exists %}
        <div class="section-video">
            <video width="1280" height="720" controls>
                <source src="{% static 'video/'|add:audio.filename|add:'.mp4' %}" type="video/mp4">
            </video>
        </div>
    {% else %}
        <p id="parNoAudio">No audio file found for this track</p>
    {% endif %}
{% endblock %}

{% block scripts %}
    <script type="application/javascript" src="{% static 'js/chunk.js' %}"></script>
{% endblock %}